Repository openshift/cluster-svcat-apiserver-operator, pull requests merged in 2019-11, with the labels that each got.

#66 add gauge showing when svcat is enabled
  manifests/0000_90_cluster-svcat-apiserver-operator_02-operator-servicemonitor.yaml
  pkg/metrics/metrics.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/version/version.go
Labels: approved, lgtm, size/M

#67 Add the version option do display git commit info
  cmd/cluster-svcat-apiserver-operator/main.go
  pkg/version/version.go
Labels: approved, lgtm, size/S

#69 Bug 1769615: Register with the legacyregistry for metrics
  Makefile
  pkg/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#70 Bug 1770109: remove the old config.crd, fix explain
  manifests/02_config.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#71 Bug 1771931: add support for trusted-ca-bundle to fix 503 error
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
