Repository openshift/cluster-svcat-apiserver-operator, pull requests merged in 2019-04, with the labels that each got.

#47 Use the CVO to manage operator config
  manifests/03_config.cr.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#46 get pod failure msg from log
  bindata/v3.11.0/openshift-svcat-apiserver/ds.yaml
  manifests/07_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#49 switch etcd to openshift-etcd
  bindata/v3.11.0/openshift-svcat-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#44 Report Operand version from Operator
  glide.lock
  glide.yaml
  manifests/07_deployment.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/quota/v1/generated.proto
  vendor/github.com/openshift/api/quota/v1/types.go
  vendor/github.com/openshift/api/tools/genswaggertypedocs/swagger_type_docs.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/rogpeppe/go-internal/testscript/testdata/exec_path_change.txt
  vendor/github.com/rogpeppe/go-internal/testscript/testdata/values.txt
  vendor/github.com/rogpeppe/go-internal/testscript/testscript.go
  vendor/github.com/rogpeppe/go-internal/testscript/testscript_test.go
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
Labels: approved, lgtm, size/XXL

#51 Add node-selector annotation to namespace
  bindata/v3.11.0/openshift-svcat-apiserver/ns.yaml
  manifests/00_namespace.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#50 go 1.11
  .travis.yml
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/S
