Repository openshift/cluster-svcat-apiserver-operator, pull requests merged in 2019-05, with the labels that each got.

#52 Fix tolerations
  manifests/07_deployment.yaml
Labels: approved, lgtm, size/S

#53 revamp README
  README.md
Labels: approved, lgtm, size/L

#54 Bug 1710569 - set prefix to /servicecatalog
  bindata/v3.11.0/openshift-svcat-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#56 Bug 1711043: ignore mgmt state of Removed
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#58 Add shawn-hurley to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#57 Add details on fresh cluster install testing
  README.md
Labels: approved, lgtm, size/M
